spring:  
  datasource: 
    url: jdbc:mysql://johanadev.com:3306/johandev_nocruelty?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: johandev_google
    password: l4,$=R38i{Nd
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
  thymeleaf:
    cache: false 
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        http-only: true
      tracking-modes:
      - cookie
#spring:  
#  datasource: 
#    url: jdbc:mysql://localhost:3306/nocruelty?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver 
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
#  thymeleaf:
#    cache: false 
#server:
#  error:
#    whitelabel:
#      enabled: false
#  servlet:
#    session:
#      cookie:
#        http-only: true
#      tracking-modes:
#      - cookie